{{- if .Values.kiko.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kui-stack.kiko.fullname" . }}-data
  labels:
    {{- include "kui-stack.kiko.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kiko.persistence.size }}
{{- end }}
