{{- if .Values.kui.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kui-stack.kui.fullname" . }}-data
  labels:
    {{- include "kui-stack.kui.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kui.persistence.size }}
{{- end }}
