apiVersion: v2
name: kui
description: kiko analytics collector + kui dashboard (stack)
type: application
version: 0.1.2
appVersion: "v0.4.3"
keywords:
  - analytics
  - dashboard
  - privacy
home: https://github.com/hrodrig/kui
sources:
  - https://github.com/hrodrig/kui
  - https://github.com/hrodrig/kiko
maintainers:
  - name: Hermes Rodriguez
    url: https://github.com/hrodrig/kui
kubeVersion: ">=1.28.0"
