apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kui-data
  namespace: kui
  labels:
    app.kubernetes.io/name: kui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
